"""Generate clean Markdown threat reports."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from analyzer.scorer import RiskAssessment, RiskLevel
from intel.queries import IntelResult

LEVEL_EMOJI = {
    RiskLevel.LOW: "🟢",
    RiskLevel.MEDIUM: "🟡",
    RiskLevel.HIGH: "🟠",
    RiskLevel.CRITICAL: "🔴",
}


def write_markdown_report(
    intel: IntelResult,
    assessment: RiskAssessment,
    output_path: str | Path,
    hash_match: dict | None = None,
) -> Path:
    """Write a Markdown report and return the output path."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    mode = intel.sources.get("mode", "free")
    mode_label = "Enhanced (API keys)" if mode == "enhanced" else "Free (zero-key)"

    lines = [
        f"# Phantom Threat Report",
        "",
        f"**Target:** `{intel.target}`  ",
        f"**Type:** {intel.target_type}  ",
        f"**Intel Mode:** {mode_label}  ",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}  ",
        "",
        "## Risk Assessment",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Threat Level | {LEVEL_EMOJI[assessment.level]} **{assessment.level.value}** |",
        f"| Risk Score | {assessment.score} / 100+ |",
        "",
        assessment.summary,
        "",
    ]

    if assessment.breakdown:
        lines += ["### Score Breakdown", ""]
        for factor, pts in assessment.breakdown.items():
            label = factor.replace("_", " ").title()
            lines.append(f"- **{label}:** +{pts}")
        lines.append("")

    if hash_match:
        lines += [
            "## Local Hash Check (C Extension)",
            "",
            f"- **Matched:** {'Yes' if hash_match.get('found') else 'No'}",
            f"- **Hash:** `{hash_match.get('hash', 'N/A')}`",
            "",
        ]

    if intel.raw_findings:
        lines += ["## Findings", ""]
        for finding in intel.raw_findings:
            lines.append(f"- {finding}")
        lines.append("")

    if intel.sources:
        lines += ["## Intelligence Sources", ""]
        for source, data in intel.sources.items():
            if source == "mode":
                continue
            lines.append(f"### {source.replace('_', ' ').title()}")
            lines.append("")
            if isinstance(data, dict):
                for key, val in data.items():
                    lines.append(f"- **{key}:** {val}")
            else:
                lines.append(f"- {data}")
            lines.append("")

    if intel.errors:
        lines += ["## Warnings", ""]
        for err in intel.errors:
            lines.append(f"- ⚠️ {err}")
        lines.append("")

    lines += [
        "---",
        "*Report generated by [Phantom](https://github.com) — personal security toolkit*",
    ]

    path.write_text("\n".join(lines), encoding="utf-8")
    return path
